project:
  type: website

website:
  title: "    "
  back-to-top-navigation: false
  navbar:
    background: transparent
    right:
      - text: home
        href: index.qmd
      - text: about
        href: about.qmd
      - icon: github
        href: https://github.com/mroberts1
      - icon: twitter
        href: https://twitter.com/mroberts_vma
format:
  html:
    backgroundcolor: "#f0f8ff"
    theme: 
      light: ember.scss
      dark: slate
    css: custom.scss
page-layout: article
linestretch: 1.2
fontsize: 0.9em
smooth-scroll: true
link-external-newwindow: true
execute:
  freeze: auto




