project:
  type: website

website:
  title: "    "
  back-to-top-navigation: false
  navbar:
    background: transparent
    right:
      - text: home
        href: index.qmd
      - text: about
        href: about.qmd
      - icon: github
        href: https://github.com/mroberts1
      - icon: twitter
        href: https://twitter.com/mroberts_vma
format:
  html:
    backgroundcolor: "#EFEDE5"
    theme: 
      light: ember.scss
      dark: slate
    css: custom.scss
    grid:
      sidebar-width: 350px
      body-width: 500px
      margin-width: 350px
      gutter-width: 2em
linestretch: 1.5
smooth-scroll: true
linkcolor: black
link-external-newwindow: true
lightbox: auto
execute:
  freeze: auto




