base_url = "/"
title = "superlocrian"
description = "writings about music"
compile_sass = true
build_search_index = true
theme = "oceanic-zen"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
highlight_theme = "visual-studio-dark"

[extra]
author = "Martin Roberts"
github = "superlocrian"
twitter = "dokoissho"
